// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaddB3rhL0bICO0fR-G_zQJXoOUcRzJHo',
    appId: '1:154055106666:web:df1c99383fbd62db6caa13',
    messagingSenderId: '154055106666',
    projectId: 'petcarelog-c9d36',
    authDomain: 'petcarelog-c9d36.firebaseapp.com',
    storageBucket: 'petcarelog-c9d36.firebasestorage.app',
    measurementId: 'G-417T3MY0N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6G7cLw3rJVpblnd2219zVmISHdetoqmo',
    appId: '1:154055106666:android:2fe2f9de2c64d48a6caa13',
    messagingSenderId: '154055106666',
    projectId: 'petcarelog-c9d36',
    storageBucket: 'petcarelog-c9d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq-rEaVSsOb4OJA51R0YamGr4AV4B-FlI',
    appId: '1:154055106666:ios:c9b3fa9ba6d08d916caa13',
    messagingSenderId: '154055106666',
    projectId: 'petcarelog-c9d36',
    storageBucket: 'petcarelog-c9d36.firebasestorage.app',
    iosBundleId: 'com.example.petCareLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq-rEaVSsOb4OJA51R0YamGr4AV4B-FlI',
    appId: '1:154055106666:ios:c9b3fa9ba6d08d916caa13',
    messagingSenderId: '154055106666',
    projectId: 'petcarelog-c9d36',
    storageBucket: 'petcarelog-c9d36.firebasestorage.app',
    iosBundleId: 'com.example.petCareLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaddB3rhL0bICO0fR-G_zQJXoOUcRzJHo',
    appId: '1:154055106666:web:9926fb402f9df9d56caa13',
    messagingSenderId: '154055106666',
    projectId: 'petcarelog-c9d36',
    authDomain: 'petcarelog-c9d36.firebaseapp.com',
    storageBucket: 'petcarelog-c9d36.firebasestorage.app',
    measurementId: 'G-1MC9VJ3GQ6',
  );
}
